version: '3.8'

services:
  app:
    build: .
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PATH_PRIVATE: ${PATH_PRIVATE}
      PATH_PUBLIC: ${PATH_PUBLIC}
      PATH_REFRESH_PRIVATE: ${PATH_REFRESH_PRIVATE}
      PATH_REFRESH_PUBLIC: ${PATH_REFRESH_PUBLIC}
    ports:
      - '8080:8080'
    volumes:
      - ./keys:/app/keys
