
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'DB_URL=${DB_URL}'
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PWD}'
      - 'POSTGRES_USER=${POSTGRES_DB_USER}'
    ports:
      - '5433:5432'
